// Code generated by "stringer -type=tokenType"; DO NOT EDIT

package parser

import "fmt"

const _tokenType_name = "tokenTypeErrortokenTypeEOFtokenTypeWhitespacetokenTypeCommenttokenTypeKeywordtokenTypeIdentifiertokenTypeNumbertokenTypeLeftBracetokenTypeRightBracetokenTypeLeftParentokenTypeRightParentokenTypeLeftBrackettokenTypeRightBrackettokenTypeEqualstokenTypeSemicolontokenTypeCommatokenTypeQuestionMarktokenTypeColon"

var _tokenType_index = [...]uint16{0, 14, 26, 45, 61, 77, 96, 111, 129, 148, 166, 185, 205, 226, 241, 259, 273, 294, 308}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return fmt.Sprintf("tokenType(%d)", i)
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
