// generated by stringer -type=TypeKind; DO NOT EDIT

package srg

import "fmt"

const _TypeKind_name = "ClassTypeInterfaceTypeNominalType"

var _TypeKind_index = [...]uint8{0, 9, 22, 33}

func (i TypeKind) String() string {
	if i < 0 || i >= TypeKind(len(_TypeKind_index)-1) {
		return fmt.Sprintf("TypeKind(%d)", i)
	}
	return _TypeKind_name[_TypeKind_index[i]:_TypeKind_index[i+1]]
}
