// Code generated by "stringer -type=TypeDiffReason"; DO NOT EDIT.

package diff

import "fmt"

const (
	_TypeDiffReason_name_0 = "TypeDiffReasonNotApplicableTypeDiffReasonKindChanged"
	_TypeDiffReason_name_1 = "TypeDiffReasonGenericsChanged"
	_TypeDiffReason_name_2 = "TypeDiffReasonExportedMembersChanged"
)

var (
	_TypeDiffReason_index_0 = [...]uint8{0, 27, 52}
	_TypeDiffReason_index_1 = [...]uint8{0, 29}
	_TypeDiffReason_index_2 = [...]uint8{0, 36}
)

func (i TypeDiffReason) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _TypeDiffReason_name_0[_TypeDiffReason_index_0[i]:_TypeDiffReason_index_0[i+1]]
	case i == 4:
		return _TypeDiffReason_name_1
	case i == 8:
		return _TypeDiffReason_name_2
	default:
		return fmt.Sprintf("TypeDiffReason(%d)", i)
	}
}
