// Code generated by "stringer -type=NodeType"; DO NOT EDIT.

package typegraph

import "fmt"

const _NodeType_name = "NodeTypeErrorNodeTypeClassNodeTypeInterfaceNodeTypeExternalInterfaceNodeTypeNominalTypeNodeTypeStructNodeTypeAgentNodeTypeModuleNodeTypeAliasNodeTypeMemberNodeTypeOperatorNodeTypeParameterNodeTypeMemberTagNodeTypeReturnableNodeTypeGenericNodeTypeAgentReferenceNodeTypeAttributeNodeTypeReportedIssueNodeTypeTagged"

var _NodeType_index = [...]uint16{0, 13, 26, 43, 68, 87, 101, 114, 128, 141, 155, 171, 188, 205, 223, 238, 260, 277, 298, 312}

func (i NodeType) String() string {
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return fmt.Sprintf("NodeType(%d)", i)
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
