// generated by stringer -type=tokenType; DO NOT EDIT

package parser

import "fmt"

const _tokenType_name = "tokenTypeErrortokenTypeEOFtokenTypeSyntheticSemicolontokenTypeWhitespacetokenTypeNewlinetokenTypeSinglelineCommenttokenTypeMultilineCommenttokenTypeColontokenTypeCommatokenTypeSemicolontokenTypeDotAccessOperatortokenTypeArrowAccessOperatortokenTypeNullDotAccessOperatortokenTypeNullOrValueOperatortokenTypeDotCastStarttokenTypeStreamAccessOperatortokenTypeArrowPortOperatortokenTypeLambdaArrowOperatortokenTypeLeftBracetokenTypeRightBracetokenTypeLeftParentokenTypeRightParentokenTypeLeftBrackettokenTypeRightBrackettokenTypeEqualstokenTypePlustokenTypeMinustokenTypeDivtokenTypeTimestokenTypeModulotokenTypeLessThantokenTypeGreaterThantokenTypeLTEtokenTypeGTEtokenTypeBitwiseShiftLefttokenTypeEqualsEqualstokenTypeNotEqualstokenTypeEllipsistokenTypeNottokenTypeTildetokenTypePipetokenTypeAndtokenTypeXortokenTypeBooleanOrtokenTypeBooleanAndtokenTypeQuestionMarktokenTypeNumericLiteraltokenTypeStringLiteraltokenTypeTemplateStringLiteraltokenTypeBooleanLiteraltokenTypeIdentifertokenTypeKeywordtokenTypeAtSign"

var _tokenType_index = [...]uint16{0, 14, 26, 53, 72, 88, 114, 139, 153, 167, 185, 211, 239, 269, 297, 318, 347, 373, 401, 419, 438, 456, 475, 495, 516, 531, 544, 558, 570, 584, 599, 616, 636, 648, 660, 685, 706, 724, 741, 753, 767, 780, 792, 804, 822, 841, 862, 885, 907, 937, 960, 978, 994, 1009}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return fmt.Sprintf("tokenType(%d)", i)
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
