// generated by stringer -type=GraphLayerKind; DO NOT EDIT

package compilergraph

import "fmt"

const _GraphLayerKind_name = "GraphLayerSRG"

var _GraphLayerKind_index = [...]uint8{0, 13}

func (i GraphLayerKind) String() string {
	if i < 0 || i >= GraphLayerKind(len(_GraphLayerKind_index)-1) {
		return fmt.Sprintf("GraphLayerKind(%d)", i)
	}
	return _GraphLayerKind_name[_GraphLayerKind_index[i]:_GraphLayerKind_index[i+1]]
}
