// generated by stringer -type=VCSKind; DO NOT EDIT

package vcs

import "fmt"

const _VCSKind_name = "VCSKindUnknownVCSKindGit"

var _VCSKind_index = [...]uint8{0, 14, 24}

func (i VCSKind) String() string {
	if i < 0 || i >= VCSKind(len(_VCSKind_index)-1) {
		return fmt.Sprintf("VCSKind(%d)", i)
	}
	return _VCSKind_name[_VCSKind_index[i]:_VCSKind_index[i+1]]
}
