// generated by stringer -type=tokenType; DO NOT EDIT

package webidl

import "fmt"

const _tokenType_name = "tokenTypeErrortokenTypeEOFtokenTypeWhitespacetokenTypeCommenttokenTypeKeywordtokenTypeIdentifiertokenTypeLeftBracetokenTypeRightBracetokenTypeLeftParentokenTypeRightParentokenTypeLeftBrackettokenTypeRightBrackettokenTypeSemicolontokenTypeComma"

var _tokenType_index = [...]uint8{0, 14, 26, 45, 61, 77, 96, 114, 133, 151, 170, 190, 211, 229, 243}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return fmt.Sprintf("tokenType(%d)", i)
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
